import Head from 'next/head'
import styles from '../../styles/home.module.css'

const Home = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Tarefa+</title>
        <meta name="description" content="Generated by Tarefa+" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>Meu projeto</h1>
    </div>
  )
}

export default Home
