import Head from 'next/head'
import styles from '../../styles/home.module.css'
import Image from 'next/image'
import heroImg from "../../public/assets/hero.png"

const Home = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Tarefa+</title>
        <meta name="description" content="Generated by Tarefa+" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

     <main className={`${styles.main} main`}>
        <div className={`${styles.logoContent} logoContent`}>
          <Image 
            className={`${styles.hero} hero`}
            alt='Logo Tarefa+'
            src={heroImg}
            priority
          />

          <h1 className={`${styles.title} title`}>
            Sistema feito para você organizar <br />
            seus estudos e tarefas
          </h1>

        </div>
     </main>
    </div>
  )
}

export default Home
